CPPIRCDIR= contrib/cppirc
OBJS= irc.o ui.o thread.o config.o irc_event_functions.o
CXXFLAGS+= `wx-config --cxxflags` -L${CPPIRCDIR} -Iinclude -I${CPPIRCDIR}
LDLIBS= `wx-config --libs` -lircinterface -lsstring

efirc: zentrale.cc $(OBJS) ${CPPIRCDIR}/libircinterface.a
	$(CXX) $(CXXFLAGS) $(OBJS) -o $(.TARGET) zentrale.cc $(LDLIBS)

irc.o irc_event_functions.o: ${CPPIRCDIR}/ircinterface.h

clean:
	-rm $(OBJS) efirc
