CPPIRCDIR:= contrib/cppirc
OBJS:= irc.o ui.o thread.o config.o irc_event_functions.o
WXCXXFLAGS:= $(shell wx-config --cxxflags)
CXXFLAGS+= $(WXCXXFLAGS) -L$(CPPIRCDIR) -Iinclude -I$(CPPIRCDIR)
LDLIBS:= $(shell wx-config --libs) -lircinterface -lsstring

efirc: zentrale.cc $(OBJS) $(CPPIRCDIR)/libircinterface.a $(CPPIRCDIR)/libsstring.a
	$(CXX) $(CXXFLAGS) $(OBJS) -o $(@) $(<) $(LDLIBS)

irc.o irc_event_functions.o: $(CPPIRCDIR)/ircinterface.h

clean:
	$(RM) $(OBJS) efirc
