CPPIRCDIR= contrib/cppirc
OBJS= irc.o ui.o thread.o config.o irc_event_functions.o
CXXFLAGS+= `wx-config --cxxflags` -L${CPPIRCDIR} -Iinclude -I${CPPIRCDIR}
LDLIBS= `wx-config --libs` -lircinterface -lsstring

efirc: $(OBJS) zentrale.cc ${CPPIRCDIR}/libircinterface.a ${CPPIRCDIR}/libsstring.a
	$(CXX) $(CXXFLAGS) $(OBJS) -o $(@) zentrale.cc $(LDLIBS)

irc.o irc_event_functions.o: ${CPPIRCDIR}/ircinterface.h

clean:
	$(RM) $(OBJS) efirc
